# Generated by Django 4.1.7 on 2023-03-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_total',
        ),
    ]
