# Generated by Django 4.1.7 on 2023-04-02 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_remove_cartitem_price_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=32)),
                ('pastOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_order', to='authuser.pastorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_order_item', to='authuser.product')),
            ],
        ),
    ]
